// Curated Miami tower directory. Static building facts; live counts come from the MLS feed.
export type Building = {
  slug: string;
  name: string;
  neighborhood: string;
  addressPrefix: string;
  city: string;
  address: string;
  yearBuilt: number;
  floors: number;
  units: number;
  hoaLow: number;
  hoaHigh: number;
  tier: "luxury" | "ultra";
  blurb: string;
};

export const NEIGHBORHOODS = [
  "Brickell",
  "Edgewater",
  "Downtown",
  "Miami Beach",
  "Sunny Isles",
] as const;

export const PRICE_TIERS: { value: string; label: string; min: number; max: number }[] = [
  { value: "", label: "Any price tier", min: 0, max: Number.POSITIVE_INFINITY },
  { value: "under1", label: "Under $1M", min: 0, max: 1_000_000 },
  { value: "1to3", label: "$1M – $3M", min: 1_000_000, max: 3_000_000 },
  { value: "3plus", label: "$3M+", min: 3_000_000, max: Number.POSITIVE_INFINITY },
];

export const BUILDINGS: Building[] = [
  {
    slug: "four-seasons-residences-brickell",
    name: "Four Seasons Residences",
    neighborhood: "Brickell",
    addressPrefix: "1425 Brickell Ave",
    city: "Miami",
    address: "1425 Brickell Avenue, Miami, FL 33131",
    yearBuilt: 2003,
    floors: 70,
    units: 186,
    hoaLow: 1900,
    hoaHigh: 6400,
    tier: "ultra",
    blurb:
      "Full-service residences above the Four Seasons hotel, with private elevators, spa access and skyline-to-bay exposures.",
  },
  {
    slug: "icon-brickell",
    name: "Icon Brickell",
    neighborhood: "Brickell",
    addressPrefix: "495 Brickell Ave",
    city: "Miami",
    address: "495 Brickell Avenue, Miami, FL 33131",
    yearBuilt: 2009,
    floors: 57,
    units: 713,
    hoaLow: 900,
    hoaHigh: 3200,
    tier: "luxury",
    blurb:
      "Philippe Starck-designed waterfront towers with a 300-foot pool deck and direct Miami River frontage.",
  },
  {
    slug: "sls-lux-brickell",
    name: "SLS LUX Brickell",
    neighborhood: "Brickell",
    addressPrefix: "801 S Miami Ave",
    city: "Miami",
    address: "801 S Miami Avenue, Miami, FL 33130",
    yearBuilt: 2018,
    floors: 57,
    units: 450,
    hoaLow: 1100,
    hoaHigh: 3600,
    tier: "luxury",
    blurb: "Art-forward hotel-branded residences across from Brickell City Centre.",
  },
  {
    slug: "brickell-flatiron",
    name: "Brickell Flatiron",
    neighborhood: "Brickell",
    addressPrefix: "1000 Brickell Plaza",
    city: "Miami",
    address: "1000 Brickell Plaza, Miami, FL 33131",
    yearBuilt: 2019,
    floors: 64,
    units: 549,
    hoaLow: 1200,
    hoaHigh: 4200,
    tier: "luxury",
    blurb: "Curved glass tower with a rooftop sky pool and 64 floors of panoramic residences.",
  },
  {
    slug: "echo-brickell",
    name: "Echo Brickell",
    neighborhood: "Brickell",
    addressPrefix: "1451 Brickell Ave",
    city: "Miami",
    address: "1451 Brickell Avenue, Miami, FL 33131",
    yearBuilt: 2017,
    floors: 57,
    units: 180,
    hoaLow: 1600,
    hoaHigh: 5200,
    tier: "ultra",
    blurb: "Boutique Carlos Ott tower with smart-home residences and a rooftop pool terrace.",
  },
  {
    slug: "aria-on-the-bay",
    name: "Aria on the Bay",
    neighborhood: "Edgewater",
    addressPrefix: "488 NE 18 St",
    city: "Miami",
    address: "488 NE 18th Street, Miami, FL 33132",
    yearBuilt: 2018,
    floors: 53,
    units: 647,
    hoaLow: 800,
    hoaHigh: 2600,
    tier: "luxury",
    blurb: "Bayfront residences overlooking Biscayne Bay and the Arsht Center district.",
  },
  {
    slug: "missoni-baia",
    name: "Missoni Baia",
    neighborhood: "Edgewater",
    addressPrefix: "700 NE 26 Ter",
    city: "Miami",
    address: "700 NE 26th Terrace, Miami, FL 33137",
    yearBuilt: 2021,
    floors: 57,
    units: 249,
    hoaLow: 1300,
    hoaHigh: 4600,
    tier: "ultra",
    blurb: "Design-house branded waterfront tower with a 75-meter lap pool on the bay.",
  },
  {
    slug: "marquis-residences",
    name: "Marquis Residences",
    neighborhood: "Downtown",
    addressPrefix: "1100 Biscayne Blvd",
    city: "Miami",
    address: "1100 Biscayne Boulevard, Miami, FL 33132",
    yearBuilt: 2008,
    floors: 67,
    units: 292,
    hoaLow: 1000,
    hoaHigh: 3400,
    tier: "luxury",
    blurb: "Glass tower on Museum Park with wide bay and Biscayne Boulevard views.",
  },
  {
    slug: "vizcayne",
    name: "Vizcayne",
    neighborhood: "Downtown",
    addressPrefix: "244 Biscayne Blvd",
    city: "Miami",
    address: "244 Biscayne Boulevard, Miami, FL 33132",
    yearBuilt: 2008,
    floors: 49,
    units: 849,
    hoaLow: 700,
    hoaHigh: 2400,
    tier: "luxury",
    blurb: "Twin towers over a two-acre amenity deck steps from Bayfront Park.",
  },
  {
    slug: "continuum-south-beach",
    name: "Continuum South Beach",
    neighborhood: "Miami Beach",
    addressPrefix: "300 S Pointe Dr",
    city: "Miami Beach",
    address: "300 S Pointe Drive, Miami Beach, FL 33139",
    yearBuilt: 1996,
    floors: 42,
    units: 318,
    hoaLow: 2200,
    hoaHigh: 8500,
    tier: "ultra",
    blurb: "Twelve-acre oceanfront compound at the southern tip of South Beach.",
  },
  {
    slug: "trump-towers-sunny-isles",
    name: "Trump Towers",
    neighborhood: "Sunny Isles",
    addressPrefix: "18001 Collins Ave",
    city: "Sunny Isles Beach",
    address: "18001 Collins Avenue, Sunny Isles Beach, FL 33160",
    yearBuilt: 2003,
    floors: 45,
    units: 813,
    hoaLow: 1100,
    hoaHigh: 4000,
    tier: "luxury",
    blurb: "Three oceanfront towers with direct beach service and full-floor penthouses.",
  },
  {
    slug: "turnberry-ocean-club",
    name: "Turnberry Ocean Club",
    neighborhood: "Sunny Isles",
    addressPrefix: "15701 Collins Ave",
    city: "Sunny Isles Beach",
    address: "15701 Collins Avenue, Sunny Isles Beach, FL 33160",
    yearBuilt: 2020,
    floors: 54,
    units: 154,
    hoaLow: 3000,
    hoaHigh: 11000,
    tier: "ultra",
    blurb: "Ultra-luxury oceanfront residences with a three-level Sky Club at the 30th floor.",
  },
  {
    slug: "jade-signature",
    name: "Jade Signature",
    neighborhood: "Sunny Isles",
    addressPrefix: "16901 Collins Ave",
    city: "Sunny Isles Beach",
    address: "16901 Collins Avenue, Sunny Isles Beach, FL 33160",
    yearBuilt: 2018,
    floors: 57,
    units: 192,
    hoaLow: 2800,
    hoaHigh: 9500,
    tier: "ultra",
    blurb: "Herzog & de Meuron oceanfront tower with beachfront amenities and open-air terraces.",
  },
];

export const getBuilding = (slug: string) => BUILDINGS.find((b) => b.slug === slug) ?? null;
