// Curated Miami tower directory. Static building facts; live counts come from the MLS feed.
export type Building = {
  slug: string;
  name: string;
  developer?: string;
  neighborhood: string;
  neighborhoodSlug: string;
  addressPrefix: string;
  city: string;
  address: string;
  yearBuilt: number;
  floors: number;
  units: number;
  hoaLow: number;
  hoaHigh: number;
  hoaRange: string;
  avgPrice: number;
  strFriendly: boolean;
  tier: "luxury" | "ultra";
  walkScore: number;
  hotspots: string[];
  amenities: string[];
  floorPlans: string[];
  similarBuildings: string[];
  blurb: string;
};

const COUNTY_BY_CITY: Record<string, "Miami-Dade" | "Broward" | "Palm Beach"> = {
  Miami: "Miami-Dade",
  "Miami Beach": "Miami-Dade",
  "Sunny Isles Beach": "Miami-Dade",
  "Bal Harbour": "Miami-Dade",
  Aventura: "Miami-Dade",
  "Key Biscayne": "Miami-Dade",
  "Coral Gables": "Miami-Dade",
  "Fort Lauderdale": "Broward",
  Hollywood: "Broward",
  "Hallandale Beach": "Broward",
  "Pompano Beach": "Broward",
  "Boca Raton": "Palm Beach",
  "Delray Beach": "Palm Beach",
  "Palm Beach": "Palm Beach",
  "West Palm Beach": "Palm Beach",
  "Riviera Beach": "Palm Beach",
};

export const countyOf = (b: Building) => COUNTY_BY_CITY[b.city] ?? "Miami-Dade";

export const PRICE_TIERS: { value: string; label: string; min: number; max: number }[] = [
  { value: "", label: "Any price tier", min: 0, max: Number.POSITIVE_INFINITY },
  { value: "under1", label: "Under $1M", min: 0, max: 1_000_000 },
  { value: "1to3", label: "$1M – $3M", min: 1_000_000, max: 3_000_000 },
  { value: "3plus", label: "$3M+", min: 3_000_000, max: Number.POSITIVE_INFINITY },
];

const AMENITY_CORE = ["24/7 concierge", "Valet parking", "Fitness center", "Resort pool deck"];

export const BUILDINGS: Building[] = [
  {
    slug: "four-seasons-residences-brickell",
    name: "Four Seasons Residences",
    neighborhood: "Brickell",
    neighborhoodSlug: "brickell",
    addressPrefix: "1425 Brickell Ave",
    city: "Miami",
    address: "1425 Brickell Avenue, Miami, FL 33131",
    yearBuilt: 2003,
    floors: 70,
    units: 186,
    hoaLow: 1900,
    hoaHigh: 6400,
    hoaRange: "$1.40–$1.85 per sq ft",
    avgPrice: 2_600_000,
    strFriendly: false,
    tier: "ultra",
    walkScore: 93,
    hotspots: ["Brickell City Centre", "Mary Brickell Village", "Simpson Park"],
    amenities: [...AMENITY_CORE, "Equinox spa access", "Private elevators", "Hotel room service"],
    floorPlans: ["01 line — 2BD/2.5BA bay", "05 line — 3BD/3.5BA corner", "Penthouse collection"],
    similarBuildings: ["echo-brickell", "brickell-flatiron", "sls-lux-brickell"],
    blurb:
      "Full-service residences above the Four Seasons hotel, with private elevators, spa access and skyline-to-bay exposures.",
  },
  {
    slug: "icon-brickell",
    name: "Icon Brickell",
    neighborhood: "Brickell",
    neighborhoodSlug: "brickell",
    addressPrefix: "495 Brickell Ave",
    city: "Miami",
    address: "495 Brickell Avenue, Miami, FL 33131",
    yearBuilt: 2009,
    floors: 57,
    units: 713,
    hoaLow: 900,
    hoaHigh: 3200,
    hoaRange: "$1.20–$1.60 per sq ft",
    avgPrice: 1_000_000,
    strFriendly: true,
    tier: "luxury",
    walkScore: 95,
    hotspots: ["Miami River Walk", "Brickell City Centre", "Bayfront Park"],
    amenities: [...AMENITY_CORE, "300-ft infinity pool", "Riverfront promenade", "Spa & sauna"],
    floorPlans: ["A line — studio", "C line — 1BD/1BA river", "E line — 2BD/2BA bay"],
    similarBuildings: ["sls-lux-brickell", "brickell-heights", "vizcayne"],
    blurb:
      "Philippe Starck-designed waterfront towers with a 300-foot pool deck and direct Miami River frontage.",
  },
  {
    slug: "sls-lux-brickell",
    name: "SLS LUX Brickell",
    neighborhood: "Brickell",
    neighborhoodSlug: "brickell",
    addressPrefix: "801 S Miami Ave",
    city: "Miami",
    address: "801 S Miami Avenue, Miami, FL 33130",
    yearBuilt: 2018,
    floors: 57,
    units: 450,
    hoaLow: 1100,
    hoaHigh: 3600,
    hoaRange: "$1.25–$1.70 per sq ft",
    avgPrice: 1_050_000,
    strFriendly: true,
    tier: "luxury",
    walkScore: 97,
    hotspots: ["Brickell City Centre", "Mary Brickell Village", "Metromover"],
    amenities: [...AMENITY_CORE, "Sky lounge", "Art collection", "Hotel services by SBE"],
    floorPlans: ["01 line — 1BD/1.5BA", "04 line — 2BD/2.5BA", "08 line — 3BD corner"],
    similarBuildings: ["icon-brickell", "brickell-heights", "brickell-flatiron"],
    blurb: "Art-forward hotel-branded residences across from Brickell City Centre.",
  },
  {
    slug: "brickell-heights",
    name: "Brickell Heights",
    neighborhood: "Brickell",
    neighborhoodSlug: "brickell",
    addressPrefix: "55 SW 9 St",
    city: "Miami",
    address: "55 SW 9th Street, Miami, FL 33130",
    yearBuilt: 2017,
    floors: 49,
    units: 690,
    hoaLow: 700,
    hoaHigh: 2400,
    hoaRange: "$1.10–$1.45 per sq ft",
    avgPrice: 950_000,
    strFriendly: true,
    tier: "luxury",
    walkScore: 98,
    hotspots: ["Brickell City Centre", "Equinox Brickell", "Metromover"],
    amenities: [...AMENITY_CORE, "Equinox gym in building", "Rooftop pool", "Co-working lounge"],
    floorPlans: ["Studio line", "1BD/1BA city", "2BD/2BA corner", "3BD penthouse"],
    similarBuildings: ["sls-lux-brickell", "icon-brickell", "brickell-flatiron"],
    blurb: "Twin towers wrapped around an Equinox flagship in the heart of Brickell.",
  },
  {
    slug: "brickell-flatiron",
    name: "Brickell Flatiron",
    neighborhood: "Brickell",
    neighborhoodSlug: "brickell",
    addressPrefix: "1000 Brickell Plaza",
    city: "Miami",
    address: "1000 Brickell Plaza, Miami, FL 33131",
    yearBuilt: 2019,
    floors: 64,
    units: 549,
    hoaLow: 1200,
    hoaHigh: 4200,
    hoaRange: "$1.30–$1.75 per sq ft",
    avgPrice: 1_300_000,
    strFriendly: false,
    tier: "luxury",
    walkScore: 97,
    hotspots: ["Brickell City Centre", "Mary Brickell Village", "Simpson Park"],
    amenities: [...AMENITY_CORE, "64th-floor sky pool", "Spa & hammam", "Residents' library"],
    floorPlans: ["02 line — 1BD/1.5BA", "06 line — 2BD/2.5BA", "Sky collection 3BD"],
    similarBuildings: ["sls-lux-brickell", "echo-brickell", "four-seasons-residences-brickell"],
    blurb: "Curved glass tower with a rooftop sky pool and 64 floors of panoramic residences.",
  },
  {
    slug: "echo-brickell",
    name: "Echo Brickell",
    neighborhood: "Brickell",
    neighborhoodSlug: "brickell",
    addressPrefix: "1451 Brickell Ave",
    city: "Miami",
    address: "1451 Brickell Avenue, Miami, FL 33131",
    yearBuilt: 2017,
    floors: 57,
    units: 180,
    hoaLow: 1600,
    hoaHigh: 5200,
    hoaRange: "$1.45–$1.90 per sq ft",
    avgPrice: 2_200_000,
    strFriendly: false,
    tier: "ultra",
    walkScore: 92,
    hotspots: ["Brickell Ave waterfront", "Brickell City Centre", "Simpson Park"],
    amenities: [...AMENITY_CORE, "Smart-home automation", "Rooftop pool terrace", "Private chef service"],
    floorPlans: ["01 line — 2BD/2.5BA bay", "03 line — 3BD/3.5BA", "Duplex penthouse"],
    similarBuildings: ["four-seasons-residences-brickell", "brickell-flatiron", "missoni-baia"],
    blurb: "Boutique Carlos Ott tower with smart-home residences and a rooftop pool terrace.",
  },
  {
    slug: "aria-on-the-bay",
    name: "Aria on the Bay",
    neighborhood: "Edgewater",
    neighborhoodSlug: "edgewater",
    addressPrefix: "488 NE 18 St",
    city: "Miami",
    address: "488 NE 18th Street, Miami, FL 33132",
    yearBuilt: 2018,
    floors: 53,
    units: 647,
    hoaLow: 800,
    hoaHigh: 2600,
    hoaRange: "$1.15–$1.50 per sq ft",
    avgPrice: 1_000_000,
    strFriendly: false,
    tier: "luxury",
    walkScore: 84,
    hotspots: ["Margaret Pace Park", "Arsht Center", "Biscayne Bay walk"],
    amenities: [...AMENITY_CORE, "Two bayfront pools", "Theater room", "Yoga studio"],
    floorPlans: ["01 line — 1BD/1.5BA", "05 line — 2BD/3BA bay", "09 line — 3BD/4BA corner"],
    similarBuildings: ["biscayne-beach", "missoni-baia", "paramount-miami"],
    blurb: "Bayfront residences overlooking Biscayne Bay and the Arsht Center district.",
  },
  {
    slug: "biscayne-beach",
    name: "Biscayne Beach",
    neighborhood: "Edgewater",
    neighborhoodSlug: "edgewater",
    addressPrefix: "2900 NE 7 Ave",
    city: "Miami",
    address: "2900 NE 7th Avenue, Miami, FL 33137",
    yearBuilt: 2017,
    floors: 52,
    units: 399,
    hoaLow: 850,
    hoaHigh: 2800,
    hoaRange: "$1.15–$1.55 per sq ft",
    avgPrice: 1_050_000,
    strFriendly: false,
    tier: "luxury",
    walkScore: 79,
    hotspots: ["Biscayne Beach Club", "Design District", "Margaret Pace Park"],
    amenities: [...AMENITY_CORE, "Private beach club", "Tennis court", "Kids' playroom"],
    floorPlans: ["02 line — 1BD/1.5BA", "06 line — 2BD/3BA bay", "Penthouse level"],
    similarBuildings: ["aria-on-the-bay", "missoni-baia", "elysee"],
    blurb: "Thom Filicia-designed bayfront tower with its own private beach club deck.",
  },
  {
    slug: "missoni-baia",
    name: "Missoni Baia",
    neighborhood: "Edgewater",
    neighborhoodSlug: "edgewater",
    addressPrefix: "700 NE 26 Ter",
    city: "Miami",
    address: "700 NE 26th Terrace, Miami, FL 33137",
    yearBuilt: 2021,
    floors: 57,
    units: 249,
    hoaLow: 1300,
    hoaHigh: 4600,
    hoaRange: "$1.35–$1.80 per sq ft",
    avgPrice: 1_800_000,
    strFriendly: false,
    tier: "ultra",
    walkScore: 78,
    hotspots: ["Design District", "Biscayne Bay walk", "Wynwood"],
    amenities: [...AMENITY_CORE, "75-meter lap pool", "Tennis court", "Missoni-designed interiors"],
    floorPlans: ["01 line — 2BD/2.5BA bay", "04 line — 3BD/4.5BA", "Sky villa"],
    similarBuildings: ["elysee", "biscayne-beach", "echo-brickell"],
    blurb: "Design-house branded waterfront tower with a 75-meter lap pool on the bay.",
  },
  {
    slug: "elysee",
    name: "Elysee",
    neighborhood: "Edgewater",
    neighborhoodSlug: "edgewater",
    addressPrefix: "700 NE 23 St",
    city: "Miami",
    address: "700 NE 23rd Street, Miami, FL 33137",
    yearBuilt: 2021,
    floors: 57,
    units: 100,
    hoaLow: 1500,
    hoaHigh: 5200,
    hoaRange: "$1.40–$1.85 per sq ft",
    avgPrice: 2_400_000,
    strFriendly: false,
    tier: "ultra",
    walkScore: 77,
    hotspots: ["Design District", "Margaret Pace Park", "Arsht Center"],
    amenities: [...AMENITY_CORE, "Sky lounge on 30", "Private dining room", "Flow-through residences"],
    floorPlans: ["East line — 3BD/3.5BA bay", "West line — 3BD/4.5BA", "Penthouse collection"],
    similarBuildings: ["missoni-baia", "biscayne-beach", "four-seasons-residences-brickell"],
    blurb: "Jean-Louis Deniot interiors in a 100-residence telescoping bayfront tower.",
  },
  {
    slug: "paramount-miami",
    name: "Paramount Miami Worldcenter",
    neighborhood: "Downtown",
    neighborhoodSlug: "downtown",
    addressPrefix: "851 NE 1 Ave",
    city: "Miami",
    address: "851 NE 1st Avenue, Miami, FL 33132",
    yearBuilt: 2019,
    floors: 60,
    units: 512,
    hoaLow: 900,
    hoaHigh: 3200,
    hoaRange: "$1.20–$1.60 per sq ft",
    avgPrice: 1_050_000,
    strFriendly: false,
    tier: "luxury",
    walkScore: 96,
    hotspots: ["Miami Worldcenter", "Kaseya Center", "Museum Park"],
    amenities: [...AMENITY_CORE, "Soccer field", "Observatory sky deck", "Two-story gym"],
    floorPlans: ["01 line — 1BD/1.5BA", "05 line — 2BD/3BA", "09 line — 3BD/4.5BA"],
    similarBuildings: ["marquis-residences", "vizcayne", "aria-on-the-bay"],
    blurb: "Amenity-heavy Worldcenter tower with an observatory deck and resort-scale recreation.",
  },
  {
    slug: "marquis-residences",
    name: "Marquis Residences",
    neighborhood: "Downtown",
    neighborhoodSlug: "downtown",
    addressPrefix: "1100 Biscayne Blvd",
    city: "Miami",
    address: "1100 Biscayne Boulevard, Miami, FL 33132",
    yearBuilt: 2008,
    floors: 67,
    units: 292,
    hoaLow: 1000,
    hoaHigh: 3400,
    hoaRange: "$1.20–$1.65 per sq ft",
    avgPrice: 1_100_000,
    strFriendly: false,
    tier: "luxury",
    walkScore: 91,
    hotspots: ["Museum Park", "Arsht Center", "Kaseya Center"],
    amenities: [...AMENITY_CORE, "Sky lounge", "Spa", "Private terraces"],
    floorPlans: ["01 line — 1BD/1.5BA", "04 line — 2BD/2.5BA bay", "Full-floor penthouse"],
    similarBuildings: ["paramount-miami", "vizcayne", "aria-on-the-bay"],
    blurb: "Glass tower on Museum Park with wide bay and Biscayne Boulevard views.",
  },
  {
    slug: "vizcayne",
    name: "Vizcayne",
    neighborhood: "Downtown",
    neighborhoodSlug: "downtown",
    addressPrefix: "244 Biscayne Blvd",
    city: "Miami",
    address: "244 Biscayne Boulevard, Miami, FL 33132",
    yearBuilt: 2008,
    floors: 49,
    units: 849,
    hoaLow: 700,
    hoaHigh: 2400,
    hoaRange: "$1.05–$1.40 per sq ft",
    avgPrice: 780_000,
    strFriendly: true,
    tier: "luxury",
    walkScore: 96,
    hotspots: ["Bayfront Park", "Bayside Marketplace", "Kaseya Center"],
    amenities: [...AMENITY_CORE, "Two-acre amenity deck", "Two pools", "Spa & sauna"],
    floorPlans: ["Studio line", "1BD/1BA bay", "2BD/2BA corner", "3BD penthouse"],
    similarBuildings: ["opera-tower", "paramount-miami", "icon-brickell"],
    blurb: "Twin towers over a two-acre amenity deck steps from Bayfront Park.",
  },
  {
    slug: "opera-tower",
    name: "Opera Tower",
    neighborhood: "Edgewater",
    neighborhoodSlug: "edgewater",
    addressPrefix: "1750 N Bayshore Dr",
    city: "Miami",
    address: "1750 N Bayshore Drive, Miami, FL 33132",
    yearBuilt: 2007,
    floors: 56,
    units: 635,
    hoaLow: 500,
    hoaHigh: 1300,
    hoaRange: "$0.95–$1.25 per sq ft",
    avgPrice: 420_000,
    strFriendly: true,
    tier: "luxury",
    walkScore: 88,
    hotspots: ["Margaret Pace Park", "Arsht Center", "Omni Metromover"],
    amenities: [...AMENITY_CORE, "Bayview pool deck", "Business center", "On-site market"],
    floorPlans: ["Studio line", "1BD/1BA bay", "2BD/2BA corner"],
    similarBuildings: ["quantum-on-the-bay", "vizcayne", "aria-on-the-bay"],
    blurb: "High-rise entry point to bayfront Edgewater with strong rental absorption.",
  },
  {
    slug: "quantum-on-the-bay",
    name: "Quantum on the Bay",
    neighborhood: "Edgewater",
    neighborhoodSlug: "edgewater",
    addressPrefix: "1900 N Bayshore Dr",
    city: "Miami",
    address: "1900 N Bayshore Drive, Miami, FL 33132",
    yearBuilt: 2008,
    floors: 51,
    units: 698,
    hoaLow: 550,
    hoaHigh: 1600,
    hoaRange: "$1.00–$1.30 per sq ft",
    avgPrice: 560_000,
    strFriendly: true,
    tier: "luxury",
    walkScore: 87,
    hotspots: ["Margaret Pace Park", "Biscayne Bay walk", "Arsht Center"],
    amenities: [...AMENITY_CORE, "Two pools", "Racquetball court", "Club room"],
    floorPlans: ["Studio line", "1BD/1BA bay", "2BD/2BA corner", "3BD line"],
    similarBuildings: ["opera-tower", "aria-on-the-bay", "biscayne-beach"],
    blurb: "Twin bayfront towers with flexible leasing and wide Biscayne Bay exposures.",
  },
  {
    slug: "midtown-2",
    name: "Midtown 2",
    neighborhood: "Midtown",
    neighborhoodSlug: "midtown",
    addressPrefix: "3470 E Coast Ave",
    city: "Miami",
    address: "3470 E Coast Avenue, Miami, FL 33137",
    yearBuilt: 2007,
    floors: 25,
    units: 337,
    hoaLow: 600,
    hoaHigh: 1700,
    hoaRange: "$1.05–$1.35 per sq ft",
    avgPrice: 650_000,
    strFriendly: true,
    tier: "luxury",
    walkScore: 92,
    hotspots: ["Design District", "Wynwood Walls", "Midtown shops"],
    amenities: [...AMENITY_CORE, "Rooftop pool", "Club lounge", "Retail at street level"],
    floorPlans: ["Studio loft", "1BD/1BA", "2BD/2BA corner"],
    similarBuildings: ["quantum-on-the-bay", "opera-tower", "biscayne-beach"],
    blurb: "Loft-style residences between Wynwood and the Design District.",
  },
  {
    slug: "continuum-south-beach",
    name: "Continuum South Beach",
    neighborhood: "Miami Beach",
    neighborhoodSlug: "miami-beach",
    addressPrefix: "300 S Pointe Dr",
    city: "Miami Beach",
    address: "300 S Pointe Drive, Miami Beach, FL 33139",
    yearBuilt: 1996,
    floors: 42,
    units: 318,
    hoaLow: 2200,
    hoaHigh: 8500,
    hoaRange: "$1.60–$2.10 per sq ft",
    avgPrice: 4_500_000,
    strFriendly: false,
    tier: "ultra",
    walkScore: 86,
    hotspots: ["South Pointe Park", "Joe's Stone Crab", "Ocean Drive"],
    amenities: [...AMENITY_CORE, "Private beach club", "Three tennis courts", "Oceanfront spa"],
    floorPlans: ["01 line — 2BD ocean", "05 line — 3BD/3.5BA", "Penthouse collection"],
    similarBuildings: ["turnberry-ocean-club", "jade-signature", "echo-brickell"],
    blurb: "Twelve-acre oceanfront compound at the southern tip of South Beach.",
  },
  {
    slug: "trump-towers-sunny-isles",
    name: "Trump Towers",
    neighborhood: "Sunny Isles",
    neighborhoodSlug: "sunny-isles",
    addressPrefix: "18001 Collins Ave",
    city: "Sunny Isles Beach",
    address: "18001 Collins Avenue, Sunny Isles Beach, FL 33160",
    yearBuilt: 2003,
    floors: 45,
    units: 813,
    hoaLow: 1100,
    hoaHigh: 4000,
    hoaRange: "$1.25–$1.70 per sq ft",
    avgPrice: 1_600_000,
    strFriendly: false,
    tier: "luxury",
    walkScore: 72,
    hotspots: ["Sunny Isles beachwalk", "Aventura Mall", "Haulover Park"],
    amenities: [...AMENITY_CORE, "Beach service", "Oceanfront spa", "Tennis courts"],
    floorPlans: ["01 line — 2BD ocean", "04 line — 3BD/3.5BA", "Full-floor penthouse"],
    similarBuildings: ["jade-signature", "turnberry-ocean-club", "continuum-south-beach"],
    blurb: "Three oceanfront towers with direct beach service and full-floor penthouses.",
  },
  {
    slug: "turnberry-ocean-club",
    name: "Turnberry Ocean Club",
    neighborhood: "Sunny Isles",
    neighborhoodSlug: "sunny-isles",
    addressPrefix: "15701 Collins Ave",
    city: "Sunny Isles Beach",
    address: "15701 Collins Avenue, Sunny Isles Beach, FL 33160",
    yearBuilt: 2020,
    floors: 54,
    units: 154,
    hoaLow: 3000,
    hoaHigh: 11000,
    hoaRange: "$1.80–$2.40 per sq ft",
    avgPrice: 5_200_000,
    strFriendly: false,
    tier: "ultra",
    walkScore: 70,
    hotspots: ["Sunny Isles beachwalk", "Bal Harbour Shops", "Haulover Park"],
    amenities: [...AMENITY_CORE, "Three-level Sky Club", "Private cinema", "Beachfront service"],
    floorPlans: ["East line — 3BD ocean", "West line — 4BD intracoastal", "Sky penthouse"],
    similarBuildings: ["jade-signature", "continuum-south-beach", "trump-towers-sunny-isles"],
    blurb: "Ultra-luxury oceanfront residences with a three-level Sky Club at the 30th floor.",
  },
  {
    slug: "jade-signature",
    name: "Jade Signature",
    neighborhood: "Sunny Isles",
    neighborhoodSlug: "sunny-isles",
    addressPrefix: "16901 Collins Ave",
    city: "Sunny Isles Beach",
    address: "16901 Collins Avenue, Sunny Isles Beach, FL 33160",
    yearBuilt: 2018,
    floors: 57,
    units: 192,
    hoaLow: 2800,
    hoaHigh: 9500,
    hoaRange: "$1.75–$2.30 per sq ft",
    avgPrice: 4_800_000,
    strFriendly: false,
    tier: "ultra",
    walkScore: 71,
    hotspots: ["Sunny Isles beachwalk", "Bal Harbour Shops", "Oleta River State Park"],
    amenities: [...AMENITY_CORE, "Beachfront restaurant", "Hammam spa", "Open-air terraces"],
    floorPlans: ["01 line — 3BD ocean", "03 line — 4BD flow-through", "Penthouse duplex"],
    similarBuildings: ["turnberry-ocean-club", "continuum-south-beach", "trump-towers-sunny-isles"],
    blurb: "Herzog & de Meuron oceanfront tower with beachfront amenities and open-air terraces.",
  },
];

export const getBuilding = (slug: string) => BUILDINGS.find((b) => b.slug === slug) ?? null;

export const buildingsInNeighborhood = (neighborhoodSlug: string) =>
  BUILDINGS.filter((b) => b.neighborhoodSlug === neighborhoodSlug);
