// Static neighborhood intelligence for Southeast Florida.
// Live pricing always comes from the MLS feed at runtime.
export type School = { name: string; level: string; rating: number };

export type Neighborhood = {
  slug: string;
  name: string;
  city: string;
  county: "Miami-Dade" | "Broward" | "Palm Beach";
  overview: string;
  lifestyle: string;
  walkScore: number;
  transitScore: number;
  schools: School[];
  investmentPotential: string;
  strZones: string[];
  strFriendly: boolean;
  hotspots: string[];
  center: { lat: number; lng: number };
  seoText: string;
};

export const COUNTIES = ["Miami-Dade", "Broward", "Palm Beach"] as const;
export type County = (typeof COUNTIES)[number];

const SCHOOLS: Record<County, School[]> = {
  "Miami-Dade": [
    { name: "Ada Merritt K-8", level: "K-8", rating: 9 },
    { name: "Design & Architecture Senior High", level: "High", rating: 10 },
    { name: "Coral Gables Senior High", level: "High", rating: 8 },
  ],
  Broward: [
    { name: "Bayview Elementary", level: "Elementary", rating: 9 },
    { name: "Sunrise Middle", level: "Middle", rating: 7 },
    { name: "Fort Lauderdale High", level: "High", rating: 8 },
  ],
  "Palm Beach": [
    { name: "Calusa Elementary", level: "Elementary", rating: 10 },
    { name: "Omni Middle", level: "Middle", rating: 9 },
    { name: "Spanish River High", level: "High", rating: 8 },
  ],
};

type Seed = Omit<Neighborhood, "schools" | "seoText"> & { schools?: School[] };

function build(seed: Seed): Neighborhood {
  return {
    ...seed,
    schools: seed.schools ?? SCHOOLS[seed.county],
    seoText: `${seed.name} real estate sits in ${seed.city}, ${seed.county} County, and Cays Realty tracks it live through the MLS. Buyers searching ${seed.name} condos, homes and rentals can compare median prices, price per square foot, active inventory and recent price drops on this page, updated continuously. ${seed.overview} Popular nearby: ${seed.hotspots.slice(0, 3).join(", ")}. ${seed.strFriendly ? "Select buildings here permit short-term and flexible leasing, which matters for investors underwriting rental income." : "Short-term rentals are restricted in most of this area, so plan on annual leases when underwriting rental income."} Talk to a Cays Realty advisor for off-market inventory and building-level history in ${seed.name}.`,
  };
}

const D = (
  slug: string,
  name: string,
  city: string,
  county: County,
  lat: number,
  lng: number,
  walkScore: number,
  transitScore: number,
  strFriendly: boolean,
  overview: string,
  lifestyle: string,
  investmentPotential: string,
  hotspots: string[],
  strZones: string[] = [],
  schools?: School[],
): Neighborhood =>
  build({
    slug,
    name,
    city,
    county,
    center: { lat, lng },
    walkScore,
    transitScore,
    strFriendly,
    overview,
    lifestyle,
    investmentPotential,
    hotspots,
    strZones,
    ...(schools ? { schools } : {}),
  });

export const NEIGHBORHOOD_LIST: Neighborhood[] = [
  /* ------------------------------ Miami-Dade ------------------------------ */
  D(
    "brickell",
    "Brickell",
    "Miami",
    "Miami-Dade",
    25.7617,
    -80.1918,
    96,
    82,
    true,
    "Miami's financial district and its densest luxury condo market, stacked along Brickell Avenue between the river and Simpson Park.",
    "Walk-everywhere urban living: Brickell City Centre, Mary Brickell Village, the Metromover loop and a restaurant scene that turns over constantly.",
    "Deepest rental pool in Miami with year-round corporate demand. Cap rates typically land in the 4–5.5% range, strongest in flexible-leasing towers.",
    ["Brickell City Centre", "Mary Brickell Village", "Miami River Walk", "Simpson Park"],
    ["Icon Brickell", "SLS LUX", "Brickell Heights"],
  ),
  D(
    "brickell-key",
    "Brickell Key",
    "Miami",
    "Miami-Dade",
    25.7686,
    -80.1839,
    78,
    70,
    false,
    "A private 44-acre island off Brickell Avenue, gated at the bridge and ringed by a bayfront jogging path.",
    "Quiet, secure island living with the Mandarin Oriental, waterfront dining and a five-minute walk to Brickell City Centre.",
    "Scarce island inventory and strong resale liquidity; rentals lease quickly to finance and consulate professionals.",
    ["Mandarin Oriental Miami", "Brickell Key Park", "Bayfront promenade"],
  ),
  D(
    "downtown",
    "Downtown Miami",
    "Miami",
    "Miami-Dade",
    25.7743,
    -80.1937,
    94,
    86,
    true,
    "The civic and cultural core — Museum Park, Kaseya Center, Bayfront Park and the Miami Worldcenter build-out.",
    "Transit-rich and event-driven, with the widest price range in the market from entry condos to full-floor penthouses.",
    "Entry pricing per square foot is the lowest of the urban core, which keeps gross yields competitive for buy-and-hold investors.",
    ["Bayfront Park", "Museum Park", "Miami Worldcenter", "Kaseya Center"],
    ["Vizcayne"],
  ),
  D(
    "edgewater",
    "Edgewater",
    "Miami",
    "Miami-Dade",
    25.7967,
    -80.1873,
    83,
    63,
    true,
    "A bayfront strip north of Downtown that has become Miami's most active new-condo corridor, with direct Biscayne Bay frontage.",
    "Quieter than Brickell, with Margaret Pace Park, the bay walk and a five-minute drive to the Design District and Wynwood.",
    "Newer inventory and bay views support above-average rent growth; appreciation has outpaced Downtown over the past cycle.",
    ["Margaret Pace Park", "Design District", "Biscayne Bay walk", "Arsht Center"],
    ["Opera Tower", "Quantum on the Bay"],
  ),
  D(
    "midtown",
    "Midtown Miami",
    "Miami",
    "Miami-Dade",
    25.8076,
    -80.1918,
    92,
    60,
    true,
    "A walkable grid of mid-rise residences and street retail wedged between Wynwood and the Design District.",
    "Gallery walks, boutique fitness and a street-level retail scene you can live in without a car.",
    "Flexible-leasing buildings and steady creative-sector tenancy make this one of the better cash-flow pockets.",
    ["Wynwood Walls", "Design District", "Midtown shops"],
    ["Midtown 2", "Midtown 4"],
  ),
  D(
    "wynwood",
    "Wynwood",
    "Miami",
    "Miami-Dade",
    25.8010,
    -80.1990,
    89,
    55,
    true,
    "Miami's arts district — murals, galleries, breweries and a new generation of loft-style residential product.",
    "Weekend crowds, chef-driven restaurants and the densest nightlife cluster outside South Beach.",
    "Live-work demand and permitted flexible leasing in newer buildings create some of the strongest gross yields in the urban core.",
    ["Wynwood Walls", "Wynwood Marketplace", "Gallery district"],
    ["Wynwood live-work overlay"],
  ),
  D(
    "design-district",
    "Design District",
    "Miami",
    "Miami-Dade",
    25.8131,
    -80.1934,
    88,
    58,
    false,
    "Luxury flagship retail, the ICA Miami and a small, tightly held residential base beside Buena Vista.",
    "Hermès to Dior on foot, courtyard cafés and one of the city's best dining rows along NE 2nd Avenue.",
    "Very limited residential supply next to the region's top retail corridor keeps values defensive through cycles.",
    ["Palm Court", "ICA Miami", "Design District shops"],
  ),
  D(
    "south-beach",
    "South Beach",
    "Miami Beach",
    "Miami-Dade",
    25.7823,
    -80.1341,
    93,
    62,
    false,
    "The Art Deco core of Miami Beach, from Lincoln Road to Ocean Drive and the Collins Avenue hotel strip.",
    "Beach-first living with Lincoln Road shopping, the Convention Center district and world-class nightlife.",
    "Appreciation-led rather than yield-led; short-term rental rules vary block by block, with MXE zones the exception.",
    ["Lincoln Road", "Ocean Drive", "Miami Beach Convention Center", "Española Way"],
    ["Designated MXE district along Collins Avenue"],
  ),
  D(
    "south-of-fifth",
    "South of Fifth",
    "Miami Beach",
    "Miami-Dade",
    25.7702,
    -80.1352,
    90,
    55,
    false,
    "The residential tip of South Beach — SoFi — with the highest price per square foot on the island.",
    "South Pointe Park, Joe's Stone Crab, marina access and a quiet, low-density street grid.",
    "Trophy oceanfront condos with the county's strongest price floor; supply almost never expands.",
    ["South Pointe Park", "Joe's Stone Crab", "Smith & Wollensky", "Marina"],
  ),
  D(
    "sunset-harbour",
    "Sunset Harbour",
    "Miami Beach",
    "Miami-Dade",
    25.7912,
    -80.1424,
    87,
    52,
    false,
    "A low-rise waterfront pocket of West Avenue known for boat slips, fitness studios and neighborhood restaurants.",
    "Walkable, local and quieter than South Beach, with the bay walk and Purdy Avenue dining.",
    "Boutique buildings and marina access attract long-term resident owners; rentals are annual, not nightly.",
    ["Sunset Harbour Yacht Club", "Purdy Avenue dining", "Maurice Gibb Park"],
  ),
  D(
    "venetian-islands",
    "Venetian Islands",
    "Miami Beach",
    "Miami-Dade",
    25.7906,
    -80.1556,
    72,
    48,
    false,
    "A chain of residential islands along the Venetian Causeway between Miami Beach and Edgewater.",
    "Waterfront single-family homes, private docks and a walkable causeway with skyline views.",
    "Land-value driven: teardowns and new-construction spec homes have delivered the strongest returns.",
    ["Venetian Causeway", "Belle Isle Park", "Sunset Harbour"],
  ),
  D(
    "fisher-island",
    "Fisher Island",
    "Fisher Island",
    "Miami-Dade",
    25.7614,
    -80.1417,
    40,
    20,
    false,
    "A ferry-only private island with one of the highest per-capita incomes in the United States.",
    "Private beach club, golf, marina, spa and total seclusion three minutes from South Beach.",
    "Ultra-scarce membership-driven market; pricing behaves independently of the broader Miami cycle.",
    ["Fisher Island Club", "Vanderbilt Mansion", "Private marina"],
  ),
  D(
    "bal-harbour",
    "Bal Harbour",
    "Bal Harbour",
    "Miami-Dade",
    25.8917,
    -80.1264,
    76,
    44,
    false,
    "An oceanfront village built around Bal Harbour Shops and a short stretch of branded beachfront towers.",
    "Luxury retail, the beach path to Haulover and quiet, tightly controlled residential streets.",
    "International buyers and hotel-branded residences support premium pricing and durable resale demand.",
    ["Bal Harbour Shops", "Haulover Park", "Bal Harbour beach path"],
  ),
  D(
    "surfside",
    "Surfside",
    "Surfside",
    "Miami-Dade",
    25.8787,
    -80.1226,
    79,
    45,
    false,
    "A small beach town between Bal Harbour and Miami Beach with a walkable Harding Avenue main street.",
    "Family-first beach living, community center, kosher dining and a quiet oceanfront.",
    "Low-density zoning and new boutique oceanfront product have reset pricing sharply upward.",
    ["Harding Avenue", "Surfside Beach", "Bal Harbour Shops"],
  ),
  D(
    "bay-harbor-islands",
    "Bay Harbor Islands",
    "Bay Harbor Islands",
    "Miami-Dade",
    25.8884,
    -80.1325,
    77,
    45,
    false,
    "Two residential islands of boutique mid-rise condos and waterfront homes beside Bal Harbour.",
    "Kane Concourse shops, top-rated K-8 schooling and a five-minute walk to the beach.",
    "A steady pipeline of boutique redevelopment plus strong school zoning supports resilient values.",
    ["Kane Concourse", "Bal Harbour Shops", "Indian Creek waterway"],
  ),
  D(
    "sunny-isles",
    "Sunny Isles Beach",
    "Sunny Isles Beach",
    "Miami-Dade",
    25.9462,
    -80.1228,
    71,
    45,
    false,
    "A two-mile oceanfront corridor of branded towers between Haulover Park and Golden Beach.",
    "Resort-style beachfront living with Bal Harbour Shops and Aventura Mall minutes away.",
    "International demand and limited oceanfront land support long-run appreciation; most towers restrict short-term rentals.",
    ["Sunny Isles beachwalk", "Bal Harbour Shops", "Haulover Park", "Aventura Mall"],
  ),
  D(
    "aventura",
    "Aventura",
    "Aventura",
    "Miami-Dade",
    25.9565,
    -80.1390,
    74,
    50,
    false,
    "A master-planned city around Aventura Mall, the Country Club and a wall of intracoastal condo towers.",
    "Mall-anchored convenience, Brightline station access, marinas and a top charter school system.",
    "Deep resale market with predictable rents; intracoastal views and renovated units drive the premium.",
    ["Aventura Mall", "Turnberry Isle", "Aventura Circle", "Brightline station"],
  ),
  D(
    "golden-beach",
    "Golden Beach",
    "Golden Beach",
    "Miami-Dade",
    25.9648,
    -80.1220,
    45,
    22,
    false,
    "A one-square-mile town of single-family oceanfront estates with no condo towers at all.",
    "Private beach pavilions, a town marina and strict residential-only zoning.",
    "Fewer than 400 homes total; new-construction oceanfront trades at the top of the Miami-Dade market.",
    ["Golden Beach town beach", "Intracoastal docks", "Sunny Isles dining"],
  ),
  D(
    "coconut-grove",
    "Coconut Grove",
    "Miami",
    "Miami-Dade",
    25.7259,
    -80.2436,
    79,
    52,
    false,
    "Miami's oldest neighborhood — waterfront estates, sailing clubs and a shaded village center.",
    "Marinas, farmers markets, CocoWalk and a family-heavy residential feel minutes from Brickell.",
    "Waterfront single-family and boutique condo product with tight supply; renovation plays remain the highest-return strategy.",
    ["CocoWalk", "Dinner Key Marina", "Vizcaya", "Peacock Park"],
    [],
    [
      { name: "Coconut Grove Elementary", level: "Elementary", rating: 9 },
      { name: "Ransom Everglades", level: "Private 6-12", rating: 10 },
      { name: "Carrollton School", level: "Private K-12", rating: 10 },
    ],
  ),
  D(
    "coral-gables",
    "Coral Gables",
    "Coral Gables",
    "Miami-Dade",
    25.7215,
    -80.2684,
    74,
    48,
    false,
    "The City Beautiful — Mediterranean-revival estates, tree-canopied streets and a low-rise single-family core.",
    "Miracle Mile, Venetian Pool, the Biltmore and the best public school zoning in the county.",
    "Single-family land value drives returns here; rental yields are modest, but price stability through downturns is the strongest in Miami-Dade.",
    ["Miracle Mile", "Venetian Pool", "Biltmore Hotel", "Merrick Park"],
    [],
    [
      { name: "Sunset Elementary", level: "Elementary", rating: 10 },
      { name: "Ponce de Leon Middle", level: "Middle", rating: 8 },
      { name: "Coral Gables Senior High", level: "High", rating: 8 },
    ],
  ),
  D(
    "pinecrest",
    "Pinecrest",
    "Pinecrest",
    "Miami-Dade",
    25.6673,
    -80.3045,
    38,
    25,
    false,
    "Large-lot suburban estates on one-acre parcels with the county's most sought-after public schools.",
    "Pinecrest Gardens, weekend farmers markets and a quiet, entirely residential street grid.",
    "Acre lots and school zoning make this the strongest family-buyer market south of the Gables.",
    ["Pinecrest Gardens", "Dadeland Mall", "Suniland Park"],
    [],
    [
      { name: "Pinecrest Elementary", level: "Elementary", rating: 10 },
      { name: "Palmetto Middle", level: "Middle", rating: 9 },
      { name: "Palmetto Senior High", level: "High", rating: 9 },
    ],
  ),
  D(
    "palmetto-bay",
    "Palmetto Bay",
    "Palmetto Bay",
    "Miami-Dade",
    25.6218,
    -80.3248,
    40,
    24,
    false,
    "A village of tree-lined residential streets and bayfront parks south of Pinecrest.",
    "Deering Estate, waterfront parks, boat ramps and a low-traffic family atmosphere.",
    "Better value per square foot than Pinecrest with the same school-driven demand profile.",
    ["Deering Estate", "Coral Reef Park", "Thalatta Estate"],
  ),
  D(
    "key-biscayne",
    "Key Biscayne",
    "Key Biscayne",
    "Miami-Dade",
    25.6937,
    -80.1626,
    62,
    30,
    false,
    "An island village between Crandon Park and Bill Baggs State Park, reached only by the Rickenbacker Causeway.",
    "Beaches, tennis, bike paths and a village center that feels like a small resort town.",
    "Island supply is fixed and demand is international; oceanfront condos and village homes both trade at a premium.",
    ["Crandon Park", "Bill Baggs Cape Florida", "Key Biscayne Village Green"],
  ),
  D(
    "miami-beach",
    "Miami Beach",
    "Miami Beach",
    "Miami-Dade",
    25.7907,
    -80.13,
    88,
    58,
    false,
    "The barrier island market as a whole — South of Fifth, South Beach, Mid-Beach and the oceanfront estate corridor.",
    "Beach-first living with Lincoln Road, Ocean Drive and the Faena cultural district.",
    "Highest price per square foot in the county; appreciation-led, with short-term rental rules that vary block by block.",
    ["South Pointe Park", "Lincoln Road", "Ocean Drive", "Faena District"],
    ["Designated MXE district along Collins Avenue"],
  ),

  /* -------------------------------- Broward -------------------------------- */
  D(
    "fort-lauderdale-beach",
    "Fort Lauderdale Beach",
    "Fort Lauderdale",
    "Broward",
    26.1224,
    -80.1050,
    82,
    48,
    true,
    "The A1A oceanfront strip from Las Olas Boulevard north to Sunrise, lined with beachfront condos and hotel residences.",
    "Beach promenade, Las Olas dining, water-taxi access and a resort-town pace year round.",
    "Vacation-rental demand supports flexible-leasing buildings; oceanfront resale liquidity is the best in Broward.",
    ["Las Olas Boulevard", "Fort Lauderdale Beach Park", "Bonnet House"],
    ["A1A hotel-residence buildings"],
  ),
  D(
    "las-olas-isles",
    "Las Olas Isles",
    "Fort Lauderdale",
    "Broward",
    26.1170,
    -80.1211,
    70,
    40,
    false,
    "Finger islands off Las Olas Boulevard where nearly every home has deep-water dockage and ocean access.",
    "Boating first: yacht dockage at the back door, Las Olas shops and restaurants at the front.",
    "Dockage depth and no-fixed-bridge access drive pricing more than square footage; yacht owners set the market.",
    ["Las Olas Boulevard", "Intracoastal Waterway", "Hendricks Isle"],
  ),
  D(
    "victoria-park",
    "Victoria Park",
    "Fort Lauderdale",
    "Broward",
    26.1310,
    -80.1330,
    76,
    45,
    false,
    "A leafy in-town neighborhood of restored bungalows and new townhomes just north of Las Olas.",
    "Walk to downtown, Holiday Park tennis and a strong neighborhood-association culture.",
    "Infill townhome development and walkability to downtown have driven consistent appreciation.",
    ["Holiday Park", "Las Olas Boulevard", "Downtown Fort Lauderdale"],
  ),
  D(
    "harbor-beach",
    "Harbor Beach",
    "Fort Lauderdale",
    "Broward",
    26.0995,
    -80.1085,
    48,
    28,
    false,
    "A gated waterfront enclave with a private beach club and 100-foot-plus dockage on wide canals.",
    "Private beach club, mega-yacht dockage and total privacy minutes from Port Everglades.",
    "The premier Broward yachting address; inventory is thin and holding periods are long.",
    ["Harbor Beach Surf Club", "Port Everglades", "Fort Lauderdale Beach"],
  ),
  D(
    "rio-vista",
    "Rio Vista",
    "Fort Lauderdale",
    "Broward",
    26.1078,
    -80.1335,
    62,
    38,
    false,
    "An established waterfront neighborhood of oak-lined streets and dockable lots south of Las Olas.",
    "Family-oriented, walkable to downtown and minutes from the beach by boat or car.",
    "New-construction waterfront replacements continue to lift the price ceiling each cycle.",
    ["Las Olas Boulevard", "Rio Vista Park", "Downtown Fort Lauderdale"],
  ),
  D(
    "lauderdale-by-the-sea",
    "Lauderdale-by-the-Sea",
    "Lauderdale-by-the-Sea",
    "Broward",
    26.1926,
    -80.0959,
    78,
    40,
    true,
    "A low-rise beach town built around a fishing pier and the only living coral reef swimmable from shore in Florida.",
    "Pier, dive shops, open-air restaurants and a genuinely walkable village center.",
    "Smaller vacation-oriented buildings with flexible leasing generate strong seasonal rental income.",
    ["Anglin's Fishing Pier", "El Prado Park", "Commercial Boulevard shops"],
    ["Village vacation-rental district"],
  ),
  D(
    "hollywood-beach",
    "Hollywood Beach",
    "Hollywood",
    "Broward",
    26.0112,
    -80.1163,
    80,
    46,
    true,
    "A 2.5-mile Broadwalk of beachfront condos, cafés and hotel residences between Fort Lauderdale and Aventura.",
    "Beachfront biking and dining on the Broadwalk with an unpretentious, year-round resort feel.",
    "One of the few Southeast Florida beaches with widespread short-term rental permission — the strongest yield story on the coast.",
    ["Hollywood Broadwalk", "Margaritaville Resort", "North Beach Park"],
    ["Broadwalk vacation-rental corridor"],
  ),
  D(
    "hallandale-beach",
    "Hallandale Beach",
    "Hallandale Beach",
    "Broward",
    25.9812,
    -80.1484,
    73,
    44,
    false,
    "A tower-lined stretch of Hollywood Beach's southern edge, between Gulfstream Park and the ocean.",
    "Gulfstream Park shopping and racing, beach access and easy Aventura proximity.",
    "Lower entry pricing than Aventura or Sunny Isles with comparable rents — the best gross yields on this coastline.",
    ["Gulfstream Park", "Hallandale Beach Boulevard", "Aventura Mall"],
  ),
  D(
    "weston",
    "Weston",
    "Weston",
    "Broward",
    26.1004,
    -80.3998,
    35,
    20,
    false,
    "A master-planned western Broward city of gated villages, lakes and A-rated schools.",
    "Golf, parks, top-rated schools and a family-first suburban layout.",
    "Consistent school-driven demand and very low vacancy; the most stable single-family market in Broward.",
    ["Weston Town Center", "Bonaventure golf", "Everglades Holiday Park"],
  ),
  D(
    "parkland",
    "Parkland",
    "Parkland",
    "Broward",
    26.3101,
    -80.2373,
    30,
    18,
    false,
    "Broward's northern edge — large-lot estate communities, equestrian trails and preserved green space.",
    "Country clubs, trails and some of the highest-rated public schools in the county.",
    "New luxury gated product and A-rated schools attract relocating families paying cash.",
    ["Parkland Golf & Country Club", "Pine Trails Park", "Heron Bay"],
  ),

  /* ------------------------------- Palm Beach ------------------------------ */
  D(
    "boca-raton",
    "Boca Raton",
    "Boca Raton",
    "Palm Beach",
    26.3683,
    -80.1289,
    52,
    30,
    false,
    "South Palm Beach County's commercial and country-club capital, from Mizner Park to the oceanfront.",
    "Mizner Park, Town Center mall, golf communities, beaches and a growing corporate base.",
    "Corporate relocation demand plus new luxury condo product has pushed Boca pricing to record levels.",
    ["Mizner Park", "Town Center at Boca Raton", "Red Reef Park", "Royal Palm Yacht Club"],
  ),
  D(
    "highland-beach",
    "Highland Beach",
    "Highland Beach",
    "Palm Beach",
    26.4001,
    -80.0653,
    42,
    22,
    false,
    "A three-mile residential barrier strip between Boca Raton and Delray Beach — oceanfront condos and intracoastal homes only.",
    "Quiet oceanfront with no commercial strip; Delray and Boca dining within minutes.",
    "Fixed supply, no commercial zoning and dual ocean-intracoastal frontage keep values tightly held.",
    ["Highland Beach oceanfront", "Atlantic Avenue Delray", "Boca Inlet"],
  ),
  D(
    "delray-beach",
    "Delray Beach",
    "Delray Beach",
    "Palm Beach",
    26.4615,
    -80.0728,
    71,
    35,
    true,
    "Atlantic Avenue's two-mile walkable main street running from the ocean into a restored downtown.",
    "Beach, galleries, the Pineapple Grove arts district and the county's liveliest dining row.",
    "A genuine walkable downtown with seasonal rental demand; boutique condos near Atlantic Avenue lease year round.",
    ["Atlantic Avenue", "Delray Municipal Beach", "Pineapple Grove", "Morikami Gardens"],
    ["Seasonal rentals near Atlantic Avenue"],
  ),
  D(
    "palm-beach-island",
    "Palm Beach Island",
    "Palm Beach",
    "Palm Beach",
    26.7056,
    -80.0364,
    58,
    26,
    false,
    "The historic island of Worth Avenue, oceanfront estates and landmarked Mediterranean architecture.",
    "Worth Avenue shopping, private clubs, the Breakers and strictly controlled development.",
    "The scarcest luxury market in Florida; estate sales regularly set statewide price records.",
    ["Worth Avenue", "The Breakers", "Lake Trail", "Flagler Museum"],
  ),
  D(
    "west-palm-beach",
    "West Palm Beach",
    "West Palm Beach",
    "Palm Beach",
    26.7153,
    -80.0534,
    68,
    42,
    false,
    "The mainland downtown across the bridge from Palm Beach — Clematis Street, CityPlace and a wave of new office and condo towers.",
    "Waterfront green space, Brightline, Kravis Center performances and a fast-expanding restaurant scene.",
    "Financial-firm relocations have reset both office and residential demand; the strongest growth trajectory in the county.",
    ["Clematis Street", "The Square", "Flagler Drive waterfront", "Brightline station"],
  ),
  D(
    "singer-island",
    "Singer Island",
    "Riviera Beach",
    "Palm Beach",
    26.7836,
    -80.0337,
    55,
    28,
    true,
    "A barrier island of oceanfront towers and hotel residences just north of Palm Beach Inlet.",
    "Wide uncrowded beaches, John D. MacArthur State Park and marina access at the inlet.",
    "Hotel-condo buildings permit flexible leasing, giving investors a rare Palm Beach short-term rental option.",
    ["MacArthur Beach State Park", "Palm Beach Inlet", "Riviera Beach Marina"],
    ["Oceanfront hotel-residence buildings"],
  ),
  D(
    "jupiter",
    "Jupiter",
    "Jupiter",
    "Palm Beach",
    26.9342,
    -80.0942,
    48,
    24,
    false,
    "A coastal town of waterfront neighborhoods, golf communities and the landmark red lighthouse at the inlet.",
    "Boating, the Riverwalk, Jupiter Beach and a relaxed family-oriented pace.",
    "Waterfront and golf-community inventory draws relocating families and athletes; supply stays tight.",
    ["Jupiter Inlet Lighthouse", "Harbourside Place", "Jupiter Beach Park", "Loxahatchee River"],
  ),
  D(
    "jupiter-island",
    "Jupiter Island",
    "Hobe Sound",
    "Palm Beach",
    27.0526,
    -80.1039,
    22,
    12,
    false,
    "A barrier island of gated oceanfront-to-intracoastal estates and one of the wealthiest zip codes in the country.",
    "Private clubs, Blowing Rocks Preserve and near-total seclusion.",
    "Estate parcels with dual frontage and multi-acre privacy; transactions are few and price records are routine.",
    ["Blowing Rocks Preserve", "Hobe Sound Beach", "Jupiter Island Club"],
  ),
];

export const getNeighborhood = (slug: string) =>
  NEIGHBORHOOD_LIST.find((n) => n.slug === slug) ?? null;

export const neighborhoodsInCounty = (county: string) =>
  NEIGHBORHOOD_LIST.filter((n) => n.county === county);
