/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SellRouteImport } from './routes/sell'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BuildingsIndexRouteImport } from './routes/buildings.index'
import { Route as BuildingsSlugRouteImport } from './routes/buildings.$slug'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as AuthenticatedAdminTrestleRouteImport } from './routes/_authenticated/admin/trestle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsIndexRoute = BuildingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildingsRoute,
} as any)
const BuildingsSlugRoute = BuildingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BuildingsRoute,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTrestleRoute =
  AuthenticatedAdminTrestleRouteImport.update({
    id: '/admin/trestle',
    path: '/admin/trestle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/buildings': typeof BuildingsRouteWithChildren
  '/compare': typeof CompareRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/buildings/$slug': typeof BuildingsSlugRoute
  '/property/$id': typeof PropertyIdRoute
  '/buildings/': typeof BuildingsIndexRoute
  '/admin/trestle': typeof AuthenticatedAdminTrestleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/buildings/$slug': typeof BuildingsSlugRoute
  '/property/$id': typeof PropertyIdRoute
  '/buildings': typeof BuildingsIndexRoute
  '/admin/trestle': typeof AuthenticatedAdminTrestleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/buildings': typeof BuildingsRouteWithChildren
  '/compare': typeof CompareRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/buildings/$slug': typeof BuildingsSlugRoute
  '/property/$id': typeof PropertyIdRoute
  '/buildings/': typeof BuildingsIndexRoute
  '/_authenticated/admin/trestle': typeof AuthenticatedAdminTrestleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/auth'
    | '/buildings'
    | '/compare'
    | '/privacy'
    | '/search'
    | '/sell'
    | '/terms'
    | '/buildings/$slug'
    | '/property/$id'
    | '/buildings/'
    | '/admin/trestle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/auth'
    | '/compare'
    | '/privacy'
    | '/search'
    | '/sell'
    | '/terms'
    | '/buildings/$slug'
    | '/property/$id'
    | '/buildings'
    | '/admin/trestle'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ask'
    | '/auth'
    | '/buildings'
    | '/compare'
    | '/privacy'
    | '/search'
    | '/sell'
    | '/terms'
    | '/buildings/$slug'
    | '/property/$id'
    | '/buildings/'
    | '/_authenticated/admin/trestle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AskRoute: typeof AskRoute
  AuthRoute: typeof AuthRoute
  BuildingsRoute: typeof BuildingsRouteWithChildren
  CompareRoute: typeof CompareRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  TermsRoute: typeof TermsRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings/': {
      id: '/buildings/'
      path: '/'
      fullPath: '/buildings/'
      preLoaderRoute: typeof BuildingsIndexRouteImport
      parentRoute: typeof BuildingsRoute
    }
    '/buildings/$slug': {
      id: '/buildings/$slug'
      path: '/$slug'
      fullPath: '/buildings/$slug'
      preLoaderRoute: typeof BuildingsSlugRouteImport
      parentRoute: typeof BuildingsRoute
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/trestle': {
      id: '/_authenticated/admin/trestle'
      path: '/admin/trestle'
      fullPath: '/admin/trestle'
      preLoaderRoute: typeof AuthenticatedAdminTrestleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminTrestleRoute: typeof AuthenticatedAdminTrestleRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminTrestleRoute: AuthenticatedAdminTrestleRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BuildingsRouteChildren {
  BuildingsSlugRoute: typeof BuildingsSlugRoute
  BuildingsIndexRoute: typeof BuildingsIndexRoute
}

const BuildingsRouteChildren: BuildingsRouteChildren = {
  BuildingsSlugRoute: BuildingsSlugRoute,
  BuildingsIndexRoute: BuildingsIndexRoute,
}

const BuildingsRouteWithChildren = BuildingsRoute._addFileChildren(
  BuildingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AskRoute: AskRoute,
  AuthRoute: AuthRoute,
  BuildingsRoute: BuildingsRouteWithChildren,
  CompareRoute: CompareRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  TermsRoute: TermsRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
